package proyectopie;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 56962
 */
public class FrameEvaluacionPart3 extends javax.swing.JFrame {

    public static String frame3_prueba_1;
    public static String frame3_prueba_2;
    public static String frame3_prueba_3;
    public static String frame3_prueba_4;
    public static String frame3_prueba_5;
    
    public static String frame3_puntaje_1;
    public static String frame3_puntaje_2;
    public static String frame3_puntaje_3;
    public static String frame3_puntaje_4;
    public static String frame3_puntaje_5;
    /**
     * Creates new form FrameEvaluacionPart3
     */
    public FrameEvaluacionPart3() {
        initComponents();
         this.setLocationRelativeTo(null);
         cargar_textfiel_pruebas();
    }
    
    void cargar_textfiel_pruebas(){
        txtprueba1.setText(frame3_prueba_1);
        txtprueba2.setText(frame3_prueba_2);
        txtprueba3.setText(frame3_prueba_3);
        txtprueba4.setText(frame3_prueba_4);
        txtprueba5.setText(frame3_prueba_5);
        
        txtpuntaje1.setText(frame3_puntaje_1);
        txtpuntaje2.setText(frame3_puntaje_2);
        txtpuntaje3.setText(frame3_puntaje_3);
        txtpuntaje4.setText(frame3_puntaje_4);
        txtpuntaje5.setText(frame3_puntaje_5);
    }
    
     
    void cargar_textfiel_pruebas_recuperar(){
        
        frame3_prueba_1 = txtprueba1.getText();
      
        frame3_prueba_2 = txtprueba2.getText();
     
        frame3_prueba_3 = txtprueba3.getText();
       
        frame3_prueba_4 = txtprueba4.getText();
       
        frame3_prueba_5 = txtprueba5.getText();
      
      
        frame3_puntaje_1 = txtpuntaje1.getText();
        
        frame3_puntaje_2 = txtpuntaje2.getText();
       
        frame3_puntaje_3 = txtpuntaje3.getText();
 
        frame3_puntaje_4 = txtpuntaje4.getText();
     
        frame3_puntaje_5 = txtpuntaje5.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtprueba1 = new javax.swing.JTextField();
        txtpuntaje1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtprueba2 = new javax.swing.JTextField();
        txtpuntaje2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtprueba3 = new javax.swing.JTextField();
        txtpuntaje3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtprueba4 = new javax.swing.JTextField();
        txtpuntaje4 = new javax.swing.JTextField();
        txtprueba5 = new javax.swing.JTextField();
        txtpuntaje5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Puntaje");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Prueba 1");

        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Pruebas");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Puntaje");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Prueba 1");

        txtprueba1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtprueba1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprueba1KeyTyped(evt);
            }
        });

        txtpuntaje1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpuntaje1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpuntaje1KeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Puntaje");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Prueba 2");

        txtprueba2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtprueba2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprueba2KeyTyped(evt);
            }
        });

        txtpuntaje2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpuntaje2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpuntaje2KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Puntaje");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Prueba 3");

        txtprueba3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtprueba3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprueba3KeyTyped(evt);
            }
        });

        txtpuntaje3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpuntaje3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpuntaje3KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Puntaje");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Prueba 4");

        txtprueba4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtprueba4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprueba4KeyTyped(evt);
            }
        });

        txtpuntaje4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpuntaje4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpuntaje4KeyTyped(evt);
            }
        });

        txtprueba5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtprueba5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprueba5KeyTyped(evt);
            }
        });

        txtpuntaje5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpuntaje5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpuntaje5KeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Puntaje");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Prueba 5");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopie/btnatras.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopie/btnsiguiente.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(320, 320, 320)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(72, 72, 72)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtprueba1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtpuntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtprueba3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtpuntaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtprueba2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtpuntaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtprueba4, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtpuntaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtprueba5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpuntaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtprueba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtpuntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtprueba2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtpuntaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtprueba3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtpuntaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtprueba4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtpuntaje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtprueba5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtpuntaje5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
  FrameEvaluacionPart2 frame = new FrameEvaluacionPart2(); 
    frame.setVisible(true);                                                                                                                
    FrameEvaluacionPart3.this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
  
    }//GEN-LAST:event_jButton2MouseClicked

    void obtener_pruebas_y_puntajes(){
        String tprueba1 = txtprueba1.getText();
        String tprueba2 = txtprueba2.getText();
        String tprueba3 = txtprueba3.getText();
        String tprueba4 = txtprueba4.getText();
        String tprueba5 = txtprueba5.getText();
        String tpuntaje1 = txtpuntaje1.getText();
        String tpuntaje2 = txtpuntaje2.getText();
        String tpuntaje3 = txtpuntaje3.getText();
        String tpuntaje4 = txtpuntaje4.getText();
        String tpuntaje5 = txtpuntaje5.getText();
        
        FrameEvaluacionPart4.prueba_1 = tprueba1;
        FrameEvaluacionPart4.prueba_2 = tprueba2;
        FrameEvaluacionPart4.prueba_3 = tprueba3;
        FrameEvaluacionPart4.prueba_4 = tprueba4;
        FrameEvaluacionPart4.prueba_5 = tprueba5;
        FrameEvaluacionPart4.puntaje_1 = tpuntaje1;
        FrameEvaluacionPart4.puntaje_2 = tpuntaje2;
        FrameEvaluacionPart4.puntaje_3 = tpuntaje3;
        FrameEvaluacionPart4.puntaje_4 = tpuntaje4;
        FrameEvaluacionPart4.puntaje_5 = tpuntaje5;
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        obtener_pruebas_y_puntajes();
        cargar_textfiel_pruebas_recuperar();
        FrameEvaluacionPart4 frame = new FrameEvaluacionPart4(); 
        frame.setVisible(true);                                                                                                                
        FrameEvaluacionPart3.this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtprueba1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprueba1KeyTyped
    
         int n=199;
         if(txtprueba1.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtprueba1KeyTyped

    private void txtprueba2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprueba2KeyTyped
   
        int n=199;
         if(txtprueba2.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtprueba2KeyTyped

    private void txtprueba3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprueba3KeyTyped
      
        int n=199;
         if(txtprueba3.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtprueba3KeyTyped

    private void txtprueba4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprueba4KeyTyped
      
        int n=199;
         if(txtprueba4.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtprueba4KeyTyped

    private void txtprueba5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprueba5KeyTyped
     
        int n=199;
         if(txtprueba5.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtprueba5KeyTyped

    private void txtpuntaje1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpuntaje1KeyTyped
      
        int n=49;
         if(txtpuntaje1.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtpuntaje1KeyTyped

    private void txtpuntaje2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpuntaje2KeyTyped
     
          int n=49;
         if(txtpuntaje2.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtpuntaje2KeyTyped

    private void txtpuntaje3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpuntaje3KeyTyped
     
          int n=49;
         if(txtpuntaje3.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtpuntaje3KeyTyped

    private void txtpuntaje4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpuntaje4KeyTyped
   
          int n=49;
         if(txtpuntaje4.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtpuntaje4KeyTyped

    private void txtpuntaje5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpuntaje5KeyTyped
   
          int n=49;
         if(txtpuntaje5.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtpuntaje5KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEvaluacionPart3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEvaluacionPart3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEvaluacionPart3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEvaluacionPart3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEvaluacionPart3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtprueba1;
    private javax.swing.JTextField txtprueba2;
    private javax.swing.JTextField txtprueba3;
    private javax.swing.JTextField txtprueba4;
    private javax.swing.JTextField txtprueba5;
    private javax.swing.JTextField txtpuntaje1;
    private javax.swing.JTextField txtpuntaje2;
    private javax.swing.JTextField txtpuntaje3;
    private javax.swing.JTextField txtpuntaje4;
    private javax.swing.JTextField txtpuntaje5;
    // End of variables declaration//GEN-END:variables
}
