package proyectopie;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 56962
 */
public class FrameDiagnostico extends javax.swing.JFrame {

    conexion con = ProyectoPIE.conexion;
    /**
     * Creates new form FrameAlumno
     */
    public FrameDiagnostico() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnombrediagnostico = new javax.swing.JTextField();
        txtdescripciondiagnostico = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopie/69594jlkjk.png"))); // NOI18N
        jLabel1.setText("    DIAGNOSTICO");
        jLabel1.setAlignmentX(0.5F);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("INGRESE NOMBRE DEL DIAGNOSTICO");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("INGRESE DESCRIPCION DEL DIAGNOSTICO");

        txtnombrediagnostico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtnombrediagnostico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombrediagnosticoKeyTyped(evt);
            }
        });

        txtdescripciondiagnostico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtdescripciondiagnostico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescripciondiagnosticoKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopie/lupa33.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopie/btnatras.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(txtnombrediagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtdescripciondiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jButton2)
                                .addGap(84, 84, 84)
                                .addComponent(jButton3)
                                .addGap(85, 85, 85)
                                .addComponent(jButton4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombrediagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdescripciondiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
      Ingresos frame3 = new Ingresos(); 
    frame3.setVisible(true);                                                                                                                
    FrameDiagnostico.this.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre_diagnostico = txtnombrediagnostico.getText();
         //String nombre_alumno = txtnombre.getText();
         //String apellido_paterno = txtapellidop.getText();
         //String apellido_materno = txtapellidom.getText();
         //Integer fono_alumno = Integer.parseInt(txtfono.getText());
         //String direccion_alumno = txtdireccion.getText();
 
        if(nombre_diagnostico.isEmpty() ){
          
         JOptionPane.showMessageDialog(null,"Debe inresar Nombre del diagnostico","ERROR",JOptionPane.ERROR_MESSAGE);
        }else
         {
             
        try{
            String sql = "select tipo_ficha.descripcion_tipoficha from tipo_ficha where tipo_ficha.nombre_tipo ='" + nombre_diagnostico +"'";
            ResultSet rs = con.ejecutarSQLSelect(sql);
            if (rs.next()){
                
                txtdescripciondiagnostico.setText(rs.getString("descripcion_tipoficha")) ;
               
                
                   
            } else{
               
              
                JOptionPane.showMessageDialog(null,"Diagnostico no existe, No olvode ingresar con puntos","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        } 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    void insertar_diagnostico(){
          String nombre_diagnostico = txtnombrediagnostico.getText();
       String descripcion_diagnostico = txtdescripciondiagnostico.getText();
      
 
        if(nombre_diagnostico.isEmpty() || descripcion_diagnostico.isEmpty() ){
          
         JOptionPane.showMessageDialog(null,"Debe inresar nombre y descripcion del diagnostico","ERROR",JOptionPane.ERROR_MESSAGE);
        }else
         {
             
        try{
             String sql = "INSERT INTO tipo_ficha (nombre_tipo,descripcion_tipoficha) VALUES ('" + nombre_diagnostico +"', '" + descripcion_diagnostico +"')";
             PreparedStatement ps=con.getConexion().prepareStatement(sql);
             ps.execute();
             ps.close();
             JOptionPane.showMessageDialog(null, "Diagnostico ingresado correctamente");
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        } 
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

          String nombre_diagnostico = txtnombrediagnostico.getText();
         //String nombre_alumno = txtnombre.getText();
         //String apellido_paterno = txtapellidop.getText();
         //String apellido_materno = txtapellidom.getText();
         //Integer fono_alumno = Integer.parseInt(txtfono.getText());
         //String direccion_alumno = txtdireccion.getText();
 
        if(nombre_diagnostico.isEmpty() ){
          
         JOptionPane.showMessageDialog(null,"Debe inresar Nombre del diagnostico","ERROR",JOptionPane.ERROR_MESSAGE);
        }else
         {
            
        try{
            String sql = "select tipo_ficha.descripcion_tipoficha from tipo_ficha where tipo_ficha.nombre_tipo ='" + nombre_diagnostico +"'";
            ResultSet rs = con.ejecutarSQLSelect(sql);
            if (rs.next()){
                
                txtdescripciondiagnostico.setText(rs.getString("descripcion_tipoficha")) ;
                 JOptionPane.showMessageDialog(null,"El Diagnostico ya existe","Informacion",JOptionPane.INFORMATION_MESSAGE);
                
                   
            } else{
               insertar_diagnostico();
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        } 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
          String nombre_diagnostico = txtnombrediagnostico.getText();
          String descripcion_diagnostico = txtdescripciondiagnostico.getText();
 
        if(nombre_diagnostico.isEmpty() ){
          
         JOptionPane.showMessageDialog(null,"No deje campos en blanco","ERROR",JOptionPane.ERROR_MESSAGE);
        }else
         {
             
        try{
             String sql = "UPDATE tipo_ficha SET nombre_tipo = '" + nombre_diagnostico +"' , descripcion_tipoficha ='" + descripcion_diagnostico +"'  WHERE nombre_tipo = '" + nombre_diagnostico +"'";
             PreparedStatement ps=con.getConexion().prepareStatement(sql);
             ps.execute();
             ps.close();
             JOptionPane.showMessageDialog(null, "Diagnostico Actualizado correctamente");
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        } 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      txtnombrediagnostico.setText("");
      txtdescripciondiagnostico.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtnombrediagnosticoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrediagnosticoKeyTyped
 
          int n=79;
        if(txtnombrediagnostico.getText().length()>=n){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
         char c=evt.getKeyChar();
        if(((c<'a' || c>'z')&&(c<'A')|c>'Z')  &&(c!='ñ')&&( c!='Ñ') &&(c!='.') )evt.consume(); 
        
         if(Character.isLowerCase(c)){
            String cad=(""+c).toUpperCase();
            c=cad.charAt(0);
            evt.setKeyChar(c);
            
        }
    }//GEN-LAST:event_txtnombrediagnosticoKeyTyped

    private void txtdescripciondiagnosticoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripciondiagnosticoKeyTyped
  
          int n=148;
        if(txtdescripciondiagnostico.getText().length()>=n){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
         char c=evt.getKeyChar();
        if(((c<'a' || c>'z')&&(c<'A')|c>'Z')  &&(c!='ñ')&&( c!='Ñ')  && (c!= KeyEvent.VK_SPACE))evt.consume(); 
        
         if(Character.isLowerCase(c)){
            String cad=(""+c).toUpperCase();
            c=cad.charAt(0);
            evt.setKeyChar(c);
            
        }
    }//GEN-LAST:event_txtdescripciondiagnosticoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtdescripciondiagnostico;
    private javax.swing.JTextField txtnombrediagnostico;
    // End of variables declaration//GEN-END:variables
}
