package proyectopie;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 56962
 */
public class FrameEvaluacionPart1 extends javax.swing.JFrame {

    conexion con = ProyectoPIE.conexion;
    public static int frame1_numero_estudiante;
    public static String frame1_diagnostico;
    public static String frame1_curso;
    public static String frame1_observacion;
    public static String frame1_sindrome_asociado;
    public static String frame1_nuevo_ingreso;
    public static String frame1_año_continuidad;
    /**
     * Creates new form FrameEvaluacionPart1
     */
    public FrameEvaluacionPart1() {
        initComponents();
         this.setLocationRelativeTo(null);
         cargar_combo_curso();
         cargar_textfield();
    }
    void cargar_textfield(){
        txtnumeroestudiante.setText(Integer.toString(frame1_numero_estudiante));
        txtobservacion.setText(frame1_observacion);
        txtsindromeasociadodiagnostico.setText(frame1_sindrome_asociado);
        txtmotivo.setText(frame1_nuevo_ingreso);
        txtañocontinuidad.setText(frame1_año_continuidad);
        txtdiagnostico.setText(frame1_diagnostico);
        combocurso.setSelectedItem(frame1_curso);
    }
    void cargar_textfield_recuperar(){
        frame1_numero_estudiante= Integer.parseInt(txtnumeroestudiante.getText());
        frame1_observacion = txtobservacion.getText();
        frame1_sindrome_asociado = txtsindromeasociadodiagnostico.getText();
        frame1_nuevo_ingreso =  txtmotivo.getText();
        frame1_año_continuidad = txtañocontinuidad.getText();
        frame1_diagnostico =   txtdiagnostico.getText();
        frame1_curso = (String) combocurso.getSelectedItem();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnumeroestudiante = new javax.swing.JTextField();
        combocurso = new javax.swing.JComboBox();
        check1 = new javax.swing.JCheckBox();
        check2 = new javax.swing.JCheckBox();
        check3 = new javax.swing.JCheckBox();
        check4 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtañocontinuidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        check5 = new javax.swing.JCheckBox();
        check6 = new javax.swing.JCheckBox();
        txtsindromeasociadodiagnostico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmotivo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdiagnostico = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtobservacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Numero del estudiante");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Curso Alumno");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Nuevo ingreso");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Continuidad");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Diagnostico");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Sindrome asociado al diagnostico");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Observacion de salud");

        txtnumeroestudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroestudianteKeyTyped(evt);
            }
        });

        combocurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        check1.setText("Si");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });

        check2.setText("No");
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });

        check3.setText("Si");
        check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check3ActionPerformed(evt);
            }
        });

        check4.setText("No");
        check4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Motivo");

        txtañocontinuidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtañocontinuidadKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Año continuidad");

        check5.setText("Si");
        check5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check5ActionPerformed(evt);
            }
        });

        check6.setText("No");
        check6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check6ActionPerformed(evt);
            }
        });

        txtsindromeasociadodiagnostico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsindromeasociadodiagnosticoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Indique cual");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopie/btnsiguiente.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopie/btnatras.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        txtmotivo.setColumns(20);
        txtmotivo.setRows(5);
        txtmotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmotivoKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtmotivo);

        txtdiagnostico.setColumns(20);
        txtdiagnostico.setRows(5);
        txtdiagnostico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiagnosticoKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtdiagnostico);

        txtobservacion.setColumns(20);
        txtobservacion.setRows(5);
        txtobservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtobservacionKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txtobservacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(check5)
                        .addGap(18, 18, 18)
                        .addComponent(check6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsindromeasociadodiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtnumeroestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(check3)
                        .addGap(18, 18, 18)
                        .addComponent(check4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtañocontinuidad, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(combocurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(check1)
                                .addGap(18, 18, 18)
                                .addComponent(check2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnumeroestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(combocurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(check1)
                            .addComponent(check2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(check3)
                            .addComponent(check4)
                            .addComponent(txtañocontinuidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(check5)
                    .addComponent(check6)
                    .addComponent(txtsindromeasociadodiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
  MenuPrincipal frame = new MenuPrincipal(); 
    frame.setVisible(true);                                                                                                                
    FrameEvaluacionPart1.this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
 
    }//GEN-LAST:event_jButton1MouseClicked

    
    void cargar_combo_curso() {
        
        
        try {
            
            String sql = "Select curso.nombre from curso ";
            ResultSet rs = con.ejecutarSQLSelect(sql);
            combocurso.removeAllItems();
            combocurso.addItem("---Selecione Curso---");
            while(rs.next()) {
                
                combocurso.addItem(rs.getString("nombre"));
                
                }
                } catch (SQLException ex) {
                                   
                 }
        
        }
    
    void obtener_id_curso() {
    
        String nombre_curso =  (String)combocurso.getSelectedItem().toString();

        try {
            
            String sql = "select curso.id_curso from curso where curso.nombre = '" + nombre_curso +"'";
            ResultSet rs = con.ejecutarSQLSelect(sql);
           
            if(rs.next()) {
                //txtnombreapoderado.setText(rs.getString("nombre_apoderado")) ;
                 int id = rs.getInt("id_curso") ;
                 FrameEvaluacionPart4.id_curso = id;
                
                }
                } catch (SQLException ex) {
                    }    
        }
    
    void concateno_palabras(){
        if (check1.isSelected()){
            String palabra = "Si "+ txtmotivo.getText();
              FrameEvaluacionPart4.nuevo_ingreso = palabra;
        }
        if(check2.isSelected()){
            String palabra = "No "+ txtmotivo.getText();
              FrameEvaluacionPart4.nuevo_ingreso = palabra;
        }
         if (check3.isSelected()){
            String palabra = "Si "+ txtañocontinuidad.getText();
              FrameEvaluacionPart4.año_continuidad = palabra;
        }
        if(check4.isSelected()){
            String palabra = "No "+ txtañocontinuidad.getText();
              FrameEvaluacionPart4.año_continuidad = palabra;
        }
         if (check5.isSelected()){
            String palabra = "Si "+ txtsindromeasociadodiagnostico.getText();
              FrameEvaluacionPart4.sindrome_asociado_diagnostico = palabra;
        }
        if(check6.isSelected()){
            String palabra = "No";
              FrameEvaluacionPart4.sindrome_asociado_diagnostico = palabra;
        }
         if (!check1.isSelected() && !check2.isSelected() ){
              String palabra = txtmotivo.getText();
              FrameEvaluacionPart4.nuevo_ingreso = palabra;
        }
           if (!check3.isSelected() && !check4.isSelected() ){
            String palabra = txtañocontinuidad.getText();
              FrameEvaluacionPart4.año_continuidad = palabra;
        }
            if (!check5.isSelected() && !check6.isSelected() ){
                String palabra = "Si "+ txtsindromeasociadodiagnostico.getText();
                FrameEvaluacionPart4.sindrome_asociado_diagnostico = palabra;   
        }       
    }
   
    void obtener_datos_textfield(){
       
        int tnumeroestudiante = Integer.parseInt(txtnumeroestudiante.getText()); 
        String tdiagnostico = txtdiagnostico.getText();
        String tobservacion = txtobservacion.getText();
        
        FrameEvaluacionPart4.numero_estudiante = tnumeroestudiante;
        FrameEvaluacionPart4.diagnostico = tdiagnostico;
        FrameEvaluacionPart4.observacion = tobservacion;
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        if (txtnumeroestudiante.getText().isEmpty()){
            
             JOptionPane.showMessageDialog(null,"Debe ingresar el numero del estudiante","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            
        
        
        obtener_id_curso();   
        concateno_palabras();
        obtener_datos_textfield();
        cargar_textfield_recuperar();
        FrameEvaluacionPart2 frame = new FrameEvaluacionPart2(); 
        frame.setVisible(true);                                                                                                                
        FrameEvaluacionPart1.this.dispose();
     
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed

        if (check2.isSelected()){
            check2.setSelected(false);
            
        }
    }//GEN-LAST:event_check1ActionPerformed

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2ActionPerformed
          if (check1.isSelected()){
            check1.setSelected(false);
          }
    }//GEN-LAST:event_check2ActionPerformed

    private void check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check3ActionPerformed
       if (check4.isSelected()){
            check4.setSelected(false);
       }  
    }//GEN-LAST:event_check3ActionPerformed

    private void check4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check4ActionPerformed
     if (check3.isSelected()){
            check3.setSelected(false);
       }  
    }//GEN-LAST:event_check4ActionPerformed

    private void check5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check5ActionPerformed
    if (check6.isSelected()){
            check6.setSelected(false);
       }  
    }//GEN-LAST:event_check5ActionPerformed

    private void check6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check6ActionPerformed
      if (check5.isSelected()){
            check5.setSelected(false);
       }  
    }//GEN-LAST:event_check6ActionPerformed

    private void txtnumeroestudianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroestudianteKeyTyped
    
            int n=3;
       if(txtnumeroestudiante.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 9 digitos","ERROR",JOptionPane.WARNING_MESSAGE);
       }
       char c=evt.getKeyChar();
               if(c<'0' || c>'9'){
                   evt.consume();
               }
    }//GEN-LAST:event_txtnumeroestudianteKeyTyped

    private void txtmotivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmotivoKeyTyped
    
            int n=299;
       if(txtmotivo.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
      
    }//GEN-LAST:event_txtmotivoKeyTyped

    private void txtañocontinuidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtañocontinuidadKeyTyped
     
         int n=19;
       if(txtañocontinuidad.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtañocontinuidadKeyTyped

    private void txtdiagnosticoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiagnosticoKeyTyped
     
         int n=599;
       if(txtdiagnostico.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtdiagnosticoKeyTyped

    private void txtsindromeasociadodiagnosticoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsindromeasociadodiagnosticoKeyTyped
   
         int n=599;
       if(txtsindromeasociadodiagnostico.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtsindromeasociadodiagnosticoKeyTyped

    private void txtobservacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtobservacionKeyTyped
   
         int n=899;
         if(txtobservacion.getText().length()>=n){
            getToolkit().beep();
           evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de caracteres","ERROR",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_txtobservacionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEvaluacionPart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEvaluacionPart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEvaluacionPart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEvaluacionPart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEvaluacionPart1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    private javax.swing.JCheckBox check3;
    private javax.swing.JCheckBox check4;
    private javax.swing.JCheckBox check5;
    private javax.swing.JCheckBox check6;
    private javax.swing.JComboBox combocurso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtañocontinuidad;
    private javax.swing.JTextArea txtdiagnostico;
    private javax.swing.JTextArea txtmotivo;
    private javax.swing.JTextField txtnumeroestudiante;
    private javax.swing.JTextArea txtobservacion;
    private javax.swing.JTextField txtsindromeasociadodiagnostico;
    // End of variables declaration//GEN-END:variables
}
